from __future__ import annotations

import logging
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def publish_report(
    report_md: str,
    date_str: str,
    config: dict[str, Any],
) -> bool:
    """Clone the reports repo, write the report, commit and push."""
    reports_repo = config.get("settings", {}).get("reports_repo", "")
    token = config.get("settings", {}).get("reports_repo_token", "")
    branch = config.get("settings", {}).get("publishing", {}).get("branch", "main")
    commit_tpl = config.get("settings", {}).get("publishing", {}).get(
        "commit_message_template", "Add daily report for {date}"
    )

    if not reports_repo:
        # Fallback: save locally
        output_dir = Path("output")
        output_dir.mkdir(exist_ok=True)
        output_path = output_dir / f"{date_str}.md"
        output_path.write_text(report_md, encoding="utf-8")
        logger.info(f"No reports repo configured. Saved locally to {output_path}")
        return True

    clone_url = f"https://x-access-token:{token}@github.com/{reports_repo}.git"

    with tempfile.TemporaryDirectory() as tmp:
        repo_dir = Path(tmp) / "reports-repo"
        try:
            # Clone
            _run(["git", "clone", "--depth", "1", "--branch", branch, clone_url, str(repo_dir)])

            # Create date directory
            year, month, _ = date_str.split("-")
            report_dir = repo_dir / "reports" / year / month
            report_dir.mkdir(parents=True, exist_ok=True)

            # Write report
            report_path = report_dir / f"{date_str}.md"
            report_path.write_text(report_md, encoding="utf-8")

            # Update README index
            _update_readme(repo_dir, date_str)

            # Commit and push
            _run(["git", "add", "."], cwd=repo_dir)
            commit_msg = commit_tpl.format(date=date_str)
            _run(["git", "commit", "-m", commit_msg], cwd=repo_dir)
            _run(["git", "push", "origin", branch], cwd=repo_dir)

            logger.info(f"Report published to {reports_repo} for {date_str}")
            return True

        except Exception as e:
            logger.error(f"Failed to publish report: {e}")
            # Save locally as fallback
            output_dir = Path("output")
            output_dir.mkdir(exist_ok=True)
            output_path = output_dir / f"{date_str}.md"
            output_path.write_text(report_md, encoding="utf-8")
            logger.info(f"Saved report locally to {output_path} as fallback")
            return False


def _run(cmd: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}\n{result.stderr}")
    return result.stdout


def _update_readme(repo_dir: Path, date_str: str) -> None:
    """Add a link to the new report in README.md's Recent Reports section."""
    readme_path = repo_dir / "README.md"
    year, month, _ = date_str.split("-")
    link = f"- [{date_str}](reports/{year}/{month}/{date_str}.md)\n"

    if readme_path.exists():
        content = readme_path.read_text(encoding="utf-8")
        marker = "## Recent Reports"
        if marker in content:
            # Insert after marker line
            parts = content.split(marker, 1)
            after = parts[1]
            # Keep max 30 entries
            lines = after.strip().split("\n")
            report_lines = [l for l in lines if l.startswith("- [")]
            report_lines.insert(0, link.strip())
            report_lines = report_lines[:30]
            remaining = [l for l in lines if not l.startswith("- [")]
            new_after = "\n" + "\n".join(report_lines) + "\n" + "\n".join(remaining)
            content = parts[0] + marker + new_after
        else:
            content += f"\n\n{marker}\n\n{link}"
    else:
        content = f"""# DeepRadar Reports

Daily AI news reports generated by [DeepRadar](https://github.com/wuqisen/DeepRadar).

## Recent Reports

{link}"""

    readme_path.write_text(content, encoding="utf-8")
