from __future__ import annotations

# Section header templates

REPORT_HEADER = """# 🔭 DeepRadar AI Daily — {date}

> {headline_en}
> {headline_zh}

---

## 📋 Executive Summary / 每日概览

{summary_en}

{summary_zh}

---
"""

GITHUB_SECTION_HEADER = """## 🔥 Hot GitHub Repos / 热门 GitHub 项目

| # | Repository | ⭐ Today | Total Stars | Language | Category |
|---|-----------|----------|-------------|----------|----------|
"""

GITHUB_TABLE_ROW = "| {idx} | [{name}]({url}) | +{stars_today} | {total_stars} | {language} | {category} |\n"

GITHUB_DETAIL = """
### [{name}]({url})
> **Why it matters / 为什么值得关注**: {why_en}
> {why_zh}

{summary_en}

{summary_zh}

"""

NEWS_SECTION_HEADER = """---

## 📰 Top AI News & Discussions / AI 热点新闻与讨论

"""

NEWS_ITEM = """### {idx}. [{title}]({url})
**Source**: {source} | **Score**: {score}/10 | **Category**: {category}

{summary_en}

{summary_zh}

> **Why it matters**: {why_en}
> **为什么重要**: {why_zh}

"""

PAPERS_SECTION_HEADER = """---

## 📄 Notable Papers / 值得关注的论文

"""

PAPER_ITEM = """### {idx}. [{title}]({url})
**Authors**: {authors} | **Categories**: {categories}

{summary_en}

{summary_zh}

"""

BLOG_SECTION_HEADER = """---

## 🏢 Industry Updates / 行业动态

"""

BLOG_ITEM = """### [{title}]({url})
**Source**: {source}

{summary_en}

{summary_zh}

"""

SOCIAL_SECTION_HEADER = """---

## 💬 Social Media Highlights / 社交媒体热点

"""

SOCIAL_TWITTER_HEADER = "### From Twitter/X\n\n"
SOCIAL_REDDIT_HEADER = "### From Reddit\n\n"
SOCIAL_YOUTUBE_HEADER = "### From YouTube\n\n"

SOCIAL_ITEM = "- **{source}**: [{title}]({url}) — {summary}\n"

SOURCE_STATUS_ITEM = "- {name}: {status}\n"

REPORT_FOOTER = """
---

## 📊 Statistics / 统计

- Total items collected: {total_collected}
- Sources active: {sources_active}/{sources_total}
- Items after dedup & filter: {items_filtered}
- Items in report: {items_in_report}
- LLM tokens used: {tokens_used}

### Source Status / 数据源状态
{source_status}
- Report generated at: {timestamp} UTC

---

*Generated by [DeepRadar](https://github.com/wuqisen/DeepRadar) — AI News Sniffer*
*Powered by Claude API*
"""
